### ISSUE TITLE
Exposed endpoint fails to connect via WebSocket in Chrome

### ISSUE THREAD

**Issue by ghost** [IgnisDa/dokku-surrealdb#13]
I can connect to the exposed SurrealDB container via SSL in Firefox and Edge. I can't connect in Chrome. 

I tried this on two different computers so not a caching issue, I don't think.

**Comment by IgnisDa** [comment]
From Discord:

> I think we're narrowing it down. Chrome loads it fine in incognito mode. There must be some plugin blocking, but I have not had this issue anywhere else which makes me concerned.

> I removed this silly adblock and replaced it with adblock plus. Now the app loads fine and makes the database call to the remote server. The adblock should have logged in console that it was blocking the request rather than waste so much of our time through process of elimination.
